apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: helloworld
spec:
  components:
    - name: helloworld
      type: webservice
      properties:
        cpu: "0.5"
        exposeType: ClusterIP
        image: oamdev/hello-world
        memory: 1024Mi
        ports:
          - expose: true
            port: 80
            protocol: TCP
      traits:
        - type: cronhpa
          properties:
            targetAPIVersion: apps/v1
            targetKind: Deployment
            excludeDates:
              - '* * * 15 11 *'
              - '* * * * * 5'
            hpaJobs:
              - name: scale-down
                runOnce: false
                schedule: "30 */1 * * * *"
                targetSize: 1
              - name: scale-up
                runOnce: false
                schedule: "0 */1 * * * *"
                targetSize: 3
  policies:
    - name: apply-once
      type: apply-once
      properties:
        enable: true
        rules:
          - strategy:
              path: ["spec.replicas"]
            selector:
              resourceTypes: ["Deployment","StatefulSet"]